version: '3.8'

services:
  catalog-server:
    build:
      context: .
      target: production
    volumes:
      - ./src/catalog-service:/app/src/catalog-service:ro
      - ./src/nginx:/app/src/nginx:ro
    ports:
      - '8001:8001'
    environment:
      - PORT=8001
      - NODE_ENV=production
  
  order-server:
    build:
      context: .
      target: production1
    volumes:
      - ./src/order-service:/app/src/order-service:ro
      - ./src/nginx:/app/src/nginx:ro
    ports:
      - '8002:8002'
    environment:
      - PORT=8002
      - NODE_ENV=production1
    depends_on:
      - nginx

 
  client:
    build:
      context: .
    volumes:
      - ./src/client-service:/app/src/client-service:ro
  nginx:
    image: nginx:stable-alpine
    ports:
      - '8083:80'
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - catalog-server

 





    